version: '3.7'
services:
  web:
    image: laravel-simple-image-gallery
    ports:
      - 8000:8000
    environment:
      XDEBUG_CONFIG: remote_host=10.255.255.255
      MYSQL_DATABASE: laravel-simple-image-gallery
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: db-laravel-simple-image-gallery
    volumes:
      - ./:/app
      - ./docker/web/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db

  db:
    container_name: db-laravel-simple-image-gallery
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel-simple-image-gallery
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
